In [23]:
import requests
import json
import pandas as pd
import plotly as plt
import time
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import urllib

%matplotlib inline

In [23]:
response = requests.get("http://metals-api.com/api/latest?access_key=anbne4hpic0ev3c2ymdyscbk5emkoni00qurxhpyrcvbuh2bu1j1yugbqbl17avu")

In [24]:
print(response.status_code)

200

In [25]:
response

In [26]:
print(response.json())

{'success': True, 'timestamp': 1578410520, 'date': '2020-01-07', 'base': 'USD', 'rates': {'AED': 3.6722191625925227, 'AFN': 77.23544328400118, 'ALL': 109.19904505032999, 'AMD': 478.7284116182215, 'ANG': 1.6849502300570585, 'AOA': 482.1372518270061, 'ARS': 59.81705892014547, 'AUD': 1.4562978095088122, 'AWG': 1.7996648679985396, 'AZN': 1.70157713380974, 'BAM': 1.7490362960065102, 'BBD': 2.0190430155937444, 'BDT': 84.89400111412989, 'BGN': 1.751318870947463, 'BHD': 0.37693080827796466, 'BIF': 1884.6490423206897, 'BMD': 0.9998138155547642, 'BND': 1.349319730872095, 'BOB': 6.914967300899745, 'BRL': 4.0892225085979685, 'BSD': 0.9999967814829942, 'BTN': 71.70039801524052, 'BWP': 10.67212064712398, 'BYN': 2.1099360895658705, 'BYR': 19596.35078487367, 'BZD': 2.0155906584886627, 'CAD': 1.3015526260201493, 'CDF': 1685.6858820645778, 'CHF': 0.9710191776668256, 'CLF': 0.028041778084864428, 'CLP': 773.9563975235677, 'CNH': 6.943404, 'CNY': 6.942707135212233, 'COP': 3251.89443509183, 'CRC': 569.0544111903946, 'CUC': 0.9998138155547642, 'CVE': 98.93148406646003, 'CZK': 22.66673402082031, 'DJF': 177.6871232609223, 'DKK': 6.7019919609793215, 'DOP': 53.19152272164218, 'DZD': 119.34274409965586, 'EEK': 14.613691, 'EGP': 16.07720511706949, 'ERN': 14.997271221405457, 'ETB': 32.05851809108992, 'EUR': 0.896793, 'FJD': 2.154799735097424, 'FKP': 0.8127286543881591, 'GBP': 0.7626229850216301, 'GEL': 2.8595045055978114, 'GGP': 0.762586991724273, 'GHS': 5.703969811782015, 'GIP': 0.8127286543881591, 'GMD': 51.210112698066084, 'GNF': 9433.243543723322, 'GTQ': 7.710213210909085, 'GYD': 208.95315892738998, 'HKD': 7.771802741761024, 'HNL': 24.620955107496126, 'HRK': 6.68117883678086, 'HTG': 98.04386235858559, 'HUF': 297.2256269064031, 'IDR': 13915.408684891247, 'ILS': 3.4695738990144807, 'IMP': 0.762586991724273, 'INR': 71.88510961840922, 'IQD': 1190.2783474179728, 'ISK': 123.13685356393987, 'JEP': 0.762586991724273, 'JMD': 132.27975698054533, 'JOD': 0.7088539978349114, 'JPY': 108.35084200194508, 'KES': 101.28374902975649, 'KGS': 69.49875700288455, 'KHR': 4077.2406348518684, 'KMF': 440.2681126611057, 'KRW': 1167.012298001102, 'KWD': 0.3031535470143615, 'KYD': 0.8333158206642467, 'KZT': 380.8060776287306, 'LAK': 8884.345707992981, 'LBP': 1512.7184319103224, 'LKR': 181.27287352567373, 'LRD': 188.5898719606923, 'LSL': 14.227141634257086, 'LTL': 2.9521902457411953, 'LVL': 0.6047773788909242, 'LYD': 1.4006241770034489, 'MAD': 9.570721748653536, 'MDL': 17.097149183986613, 'MGA': 3707.3215278611083, 'MKD': 54.98853008451903, 'MMK': 1463.9827814201503, 'MNT': 2741.898744038786, 'MOP': 8.006308072385652, 'MRO': 356.9333661839532, 'MTL': 0.683738, 'MUR': 36.44685189944629, 'MVR': 15.446876496309033, 'MWK': 739.8616816114351, 'MXN': 18.90841889094288, 'MYR': 4.103215902760414, 'MZN': 61.69348549364735, 'NAD': 14.227617545632597, 'NGN': 362.4319442436125, 'NIO': 33.73598571455113, 'NOK': 8.859525187048483, 'NPR': 114.72077679831429, 'NZD': 1.5084740932872966, 'OMR': 0.38495031489252424, 'PAB': 1.0000417731047018, 'PEN': 3.325883656884341, 'PGK': 3.4099649993311183, 'PHP': 50.88555513688803, 'PKR': 154.92174760906138, 'PLN': 3.808140851375767, 'PYG': 6505.13701813283, 'QAR': 3.6402771108131886, 'RON': 4.284632119592828, 'RSD': 105.3753470959787, 'RUB': 62.08953974077505, 'RWF': 934.82591754374, 'SAR': 3.750763536128672, 'SBD': 8.30235594261282, 'SCR': 13.697872194344384, 'SEK': 9.462162964374256, 'SGD': 1.3504585188079823, 'SHP': 1.3206490698972126, 'SLL': 9773.180235012376, 'SOS': 579.8925099292278, 'SRD': 7.456669425608679, 'SSP': 130.26, 'STD': 21556.775716275326, 'SVC': 8.74951667273683, 'SZL': 14.227462574491389, 'THB': 30.299379676291412, 'TJS': 9.697530134507478, 'TMT': 3.509346492597193, 'TND': 2.7815120292878404, 'TOP': 2.2887717869403343, 'TRY': 5.975652219324139, 'TTD': 6.7616218567528374, 'TWD': 30.053397482877582, 'TZS': 2299.8870140725835, 'UAH': 23.72886023261564, 'UGX': 3709.780666922433, 'UYU': 37.29498596067013, 'UZS': 9547.5430959611, 'VEF': 9.985637483411407, 'VES': 33474.855, 'VND': 23175.780226685834, 'VUV': 115.64850703721713, 'WST': 2.6218657584752543, 'XAF': 0.0017046745166453216, 'XAG': 18.213020233016607, 'XAU': 1570.1510504181074, 'XCD': 0.3700898111473702, 'XDR': 1.3833222030509622, 'XOF': 0.0017047355316867445, 'XPD': 2047.921359819783, 'XPF': 0.009334457793393898, 'XPT': 961.9917076314803, 'XRH': 0.0001777027137821067, 'YER': 250.30342971649765, 'ZAR': 14.326733088424522, 'ZMK': 8999.527430954533, 'ZMW': 14.159300267616462, 'ZWL': 321.9400496084483}, 'unit': 'per ounce'}

In [27]:
# STORING METALS API JSON RESULT IN RES VARIABLE

metalsApiRes = response.json()

In [28]:
# STORING RATES DATA INTO RATES VARIABLE

metalsApiRates = metalsApiRes["rates"]

In [29]:
print(metalsApiRes)

{'success': True, 'timestamp': 1578410520, 'date': '2020-01-07', 'base': 'USD', 'rates': {'AED': 3.6722191625925227, 'AFN': 77.23544328400118, 'ALL': 109.19904505032999, 'AMD': 478.7284116182215, 'ANG': 1.6849502300570585, 'AOA': 482.1372518270061, 'ARS': 59.81705892014547, 'AUD': 1.4562978095088122, 'AWG': 1.7996648679985396, 'AZN': 1.70157713380974, 'BAM': 1.7490362960065102, 'BBD': 2.0190430155937444, 'BDT': 84.89400111412989, 'BGN': 1.751318870947463, 'BHD': 0.37693080827796466, 'BIF': 1884.6490423206897, 'BMD': 0.9998138155547642, 'BND': 1.349319730872095, 'BOB': 6.914967300899745, 'BRL': 4.0892225085979685, 'BSD': 0.9999967814829942, 'BTN': 71.70039801524052, 'BWP': 10.67212064712398, 'BYN': 2.1099360895658705, 'BYR': 19596.35078487367, 'BZD': 2.0155906584886627, 'CAD': 1.3015526260201493, 'CDF': 1685.6858820645778, 'CHF': 0.9710191776668256, 'CLF': 0.028041778084864428, 'CLP': 773.9563975235677, 'CNH': 6.943404, 'CNY': 6.942707135212233, 'COP': 3251.89443509183, 'CRC': 569.0544111903946, 'CUC': 0.9998138155547642, 'CVE': 98.93148406646003, 'CZK': 22.66673402082031, 'DJF': 177.6871232609223, 'DKK': 6.7019919609793215, 'DOP': 53.19152272164218, 'DZD': 119.34274409965586, 'EEK': 14.613691, 'EGP': 16.07720511706949, 'ERN': 14.997271221405457, 'ETB': 32.05851809108992, 'EUR': 0.896793, 'FJD': 2.154799735097424, 'FKP': 0.8127286543881591, 'GBP': 0.7626229850216301, 'GEL': 2.8595045055978114, 'GGP': 0.762586991724273, 'GHS': 5.703969811782015, 'GIP': 0.8127286543881591, 'GMD': 51.210112698066084, 'GNF': 9433.243543723322, 'GTQ': 7.710213210909085, 'GYD': 208.95315892738998, 'HKD': 7.771802741761024, 'HNL': 24.620955107496126, 'HRK': 6.68117883678086, 'HTG': 98.04386235858559, 'HUF': 297.2256269064031, 'IDR': 13915.408684891247, 'ILS': 3.4695738990144807, 'IMP': 0.762586991724273, 'INR': 71.88510961840922, 'IQD': 1190.2783474179728, 'ISK': 123.13685356393987, 'JEP': 0.762586991724273, 'JMD': 132.27975698054533, 'JOD': 0.7088539978349114, 'JPY': 108.35084200194508, 'KES': 101.28374902975649, 'KGS': 69.49875700288455, 'KHR': 4077.2406348518684, 'KMF': 440.2681126611057, 'KRW': 1167.012298001102, 'KWD': 0.3031535470143615, 'KYD': 0.8333158206642467, 'KZT': 380.8060776287306, 'LAK': 8884.345707992981, 'LBP': 1512.7184319103224, 'LKR': 181.27287352567373, 'LRD': 188.5898719606923, 'LSL': 14.227141634257086, 'LTL': 2.9521902457411953, 'LVL': 0.6047773788909242, 'LYD': 1.4006241770034489, 'MAD': 9.570721748653536, 'MDL': 17.097149183986613, 'MGA': 3707.3215278611083, 'MKD': 54.98853008451903, 'MMK': 1463.9827814201503, 'MNT': 2741.898744038786, 'MOP': 8.006308072385652, 'MRO': 356.9333661839532, 'MTL': 0.683738, 'MUR': 36.44685189944629, 'MVR': 15.446876496309033, 'MWK': 739.8616816114351, 'MXN': 18.90841889094288, 'MYR': 4.103215902760414, 'MZN': 61.69348549364735, 'NAD': 14.227617545632597, 'NGN': 362.4319442436125, 'NIO': 33.73598571455113, 'NOK': 8.859525187048483, 'NPR': 114.72077679831429, 'NZD': 1.5084740932872966, 'OMR': 0.38495031489252424, 'PAB': 1.0000417731047018, 'PEN': 3.325883656884341, 'PGK': 3.4099649993311183, 'PHP': 50.88555513688803, 'PKR': 154.92174760906138, 'PLN': 3.808140851375767, 'PYG': 6505.13701813283, 'QAR': 3.6402771108131886, 'RON': 4.284632119592828, 'RSD': 105.3753470959787, 'RUB': 62.08953974077505, 'RWF': 934.82591754374, 'SAR': 3.750763536128672, 'SBD': 8.30235594261282, 'SCR': 13.697872194344384, 'SEK': 9.462162964374256, 'SGD': 1.3504585188079823, 'SHP': 1.3206490698972126, 'SLL': 9773.180235012376, 'SOS': 579.8925099292278, 'SRD': 7.456669425608679, 'SSP': 130.26, 'STD': 21556.775716275326, 'SVC': 8.74951667273683, 'SZL': 14.227462574491389, 'THB': 30.299379676291412, 'TJS': 9.697530134507478, 'TMT': 3.509346492597193, 'TND': 2.7815120292878404, 'TOP': 2.2887717869403343, 'TRY': 5.975652219324139, 'TTD': 6.7616218567528374, 'TWD': 30.053397482877582, 'TZS': 2299.8870140725835, 'UAH': 23.72886023261564, 'UGX': 3709.780666922433, 'UYU': 37.29498596067013, 'UZS': 9547.5430959611, 'VEF': 9.985637483411407, 'VES': 33474.855, 'VND': 23175.780226685834, 'VUV': 115.64850703721713, 'WST': 2.6218657584752543, 'XAF': 0.0017046745166453216, 'XAG': 18.213020233016607, 'XAU': 1570.1510504181074, 'XCD': 0.3700898111473702, 'XDR': 1.3833222030509622, 'XOF': 0.0017047355316867445, 'XPD': 2047.921359819783, 'XPF': 0.009334457793393898, 'XPT': 961.9917076314803, 'XRH': 0.0001777027137821067, 'YER': 250.30342971649765, 'ZAR': 14.326733088424522, 'ZMK': 8999.527430954533, 'ZMW': 14.159300267616462, 'ZWL': 321.9400496084483}, 'unit': 'per ounce'}

In [30]:
metalsApiRates

{'AED': 3.6722191625925227,
 'AFN': 77.23544328400118,
 'ALL': 109.19904505032999,
 'AMD': 478.7284116182215,
 'ANG': 1.6849502300570585,
 'AOA': 482.1372518270061,
 'ARS': 59.81705892014547,
 'AUD': 1.4562978095088122,
 'AWG': 1.7996648679985396,
 'AZN': 1.70157713380974,
 'BAM': 1.7490362960065102,
 'BBD': 2.0190430155937444,
 'BDT': 84.89400111412989,
 'BGN': 1.751318870947463,
 'BHD': 0.37693080827796466,
 'BIF': 1884.6490423206897,
 'BMD': 0.9998138155547642,
 'BND': 1.349319730872095,
 'BOB': 6.914967300899745,
 'BRL': 4.0892225085979685,
 'BSD': 0.9999967814829942,
 'BTN': 71.70039801524052,
 'BWP': 10.67212064712398,
 'BYN': 2.1099360895658705,
 'BYR': 19596.35078487367,
 'BZD': 2.0155906584886627,
 'CAD': 1.3015526260201493,
 'CDF': 1685.6858820645778,
 'CHF': 0.9710191776668256,
 'CLF': 0.028041778084864428,
 'CLP': 773.9563975235677,
 'CNH': 6.943404,
 'CNY': 6.942707135212233,
 'COP': 3251.89443509183,
 'CRC': 569.0544111903946,
 'CUC': 0.9998138155547642,
 'CVE': 98.93148406646003,
 'CZK': 22.66673402082031,
 'DJF': 177.6871232609223,
 'DKK': 6.7019919609793215,
 'DOP': 53.19152272164218,
 'DZD': 119.34274409965586,
 'EEK': 14.613691,
 'EGP': 16.07720511706949,
 'ERN': 14.997271221405457,
 'ETB': 32.05851809108992,
 'EUR': 0.896793,
 'FJD': 2.154799735097424,
 'FKP': 0.8127286543881591,
 'GBP': 0.7626229850216301,
 'GEL': 2.8595045055978114,
 'GGP': 0.762586991724273,
 'GHS': 5.703969811782015,
 'GIP': 0.8127286543881591,
 'GMD': 51.210112698066084,
 'GNF': 9433.243543723322,
 'GTQ': 7.710213210909085,
 'GYD': 208.95315892738998,
 'HKD': 7.771802741761024,
 'HNL': 24.620955107496126,
 'HRK': 6.68117883678086,
 'HTG': 98.04386235858559,
 'HUF': 297.2256269064031,
 'IDR': 13915.408684891247,
 'ILS': 3.4695738990144807,
 'IMP': 0.762586991724273,
 'INR': 71.88510961840922,
 'IQD': 1190.2783474179728,
 'ISK': 123.13685356393987,
 'JEP': 0.762586991724273,
 'JMD': 132.27975698054533,
 'JOD': 0.7088539978349114,
 'JPY': 108.35084200194508,
 'KES': 101.28374902975649,
 'KGS': 69.49875700288455,
 'KHR': 4077.2406348518684,
 'KMF': 440.2681126611057,
 'KRW': 1167.012298001102,
 'KWD': 0.3031535470143615,
 'KYD': 0.8333158206642467,
 'KZT': 380.8060776287306,
 'LAK': 8884.345707992981,
 'LBP': 1512.7184319103224,
 'LKR': 181.27287352567373,
 'LRD': 188.5898719606923,
 'LSL': 14.227141634257086,
 'LTL': 2.9521902457411953,
 'LVL': 0.6047773788909242,
 'LYD': 1.4006241770034489,
 'MAD': 9.570721748653536,
 'MDL': 17.097149183986613,
 'MGA': 3707.3215278611083,
 'MKD': 54.98853008451903,
 'MMK': 1463.9827814201503,
 'MNT': 2741.898744038786,
 'MOP': 8.006308072385652,
 'MRO': 356.9333661839532,
 'MTL': 0.683738,
 'MUR': 36.44685189944629,
 'MVR': 15.446876496309033,
 'MWK': 739.8616816114351,
 'MXN': 18.90841889094288,
 'MYR': 4.103215902760414,
 'MZN': 61.69348549364735,
 'NAD': 14.227617545632597,
 'NGN': 362.4319442436125,
 'NIO': 33.73598571455113,
 'NOK': 8.859525187048483,
 'NPR': 114.72077679831429,
 'NZD': 1.5084740932872966,
 'OMR': 0.38495031489252424,
 'PAB': 1.0000417731047018,
 'PEN': 3.325883656884341,
 'PGK': 3.4099649993311183,
 'PHP': 50.88555513688803,
 'PKR': 154.92174760906138,
 'PLN': 3.808140851375767,
 'PYG': 6505.13701813283,
 'QAR': 3.6402771108131886,
 'RON': 4.284632119592828,
 'RSD': 105.3753470959787,
 'RUB': 62.08953974077505,
 'RWF': 934.82591754374,
 'SAR': 3.750763536128672,
 'SBD': 8.30235594261282,
 'SCR': 13.697872194344384,
 'SEK': 9.462162964374256,
 'SGD': 1.3504585188079823,
 'SHP': 1.3206490698972126,
 'SLL': 9773.180235012376,
 'SOS': 579.8925099292278,
 'SRD': 7.456669425608679,
 'SSP': 130.26,
 'STD': 21556.775716275326,
 'SVC': 8.74951667273683,
 'SZL': 14.227462574491389,
 'THB': 30.299379676291412,
 'TJS': 9.697530134507478,
 'TMT': 3.509346492597193,
 'TND': 2.7815120292878404,
 'TOP': 2.2887717869403343,
 'TRY': 5.975652219324139,
 'TTD': 6.7616218567528374,
 'TWD': 30.053397482877582,
 'TZS': 2299.8870140725835,
 'UAH': 23.72886023261564,
 'UGX': 3709.780666922433,
 'UYU': 37.29498596067013,
 'UZS': 9547.5430959611,
 'VEF': 9.985637483411407,
 'VES': 33474.855,
 'VND': 23175.780226685834,
 'VUV': 115.64850703721713,
 'WST': 2.6218657584752543,
 'XAF': 0.0017046745166453216,
 'XAG': 18.213020233016607,
 'XAU': 1570.1510504181074,
 'XCD': 0.3700898111473702,
 'XDR': 1.3833222030509622,
 'XOF': 0.0017047355316867445,
 'XPD': 2047.921359819783,
 'XPF': 0.009334457793393898,
 'XPT': 961.9917076314803,
 'XRH': 0.0001777027137821067,
 'YER': 250.30342971649765,
 'ZAR': 14.326733088424522,
 'ZMK': 8999.527430954533,
 'ZMW': 14.159300267616462,
 'ZWL': 321.9400496084483}

In [31]:
metalsApiRates

{'AED': 3.6722191625925227,
 'AFN': 77.23544328400118,
 'ALL': 109.19904505032999,
 'AMD': 478.7284116182215,
 'ANG': 1.6849502300570585,
 'AOA': 482.1372518270061,
 'ARS': 59.81705892014547,
 'AUD': 1.4562978095088122,
 'AWG': 1.7996648679985396,
 'AZN': 1.70157713380974,
 'BAM': 1.7490362960065102,
 'BBD': 2.0190430155937444,
 'BDT': 84.89400111412989,
 'BGN': 1.751318870947463,
 'BHD': 0.37693080827796466,
 'BIF': 1884.6490423206897,
 'BMD': 0.9998138155547642,
 'BND': 1.349319730872095,
 'BOB': 6.914967300899745,
 'BRL': 4.0892225085979685,
 'BSD': 0.9999967814829942,
 'BTN': 71.70039801524052,
 'BWP': 10.67212064712398,
 'BYN': 2.1099360895658705,
 'BYR': 19596.35078487367,
 'BZD': 2.0155906584886627,
 'CAD': 1.3015526260201493,
 'CDF': 1685.6858820645778,
 'CHF': 0.9710191776668256,
 'CLF': 0.028041778084864428,
 'CLP': 773.9563975235677,
 'CNH': 6.943404,
 'CNY': 6.942707135212233,
 'COP': 3251.89443509183,
 'CRC': 569.0544111903946,
 'CUC': 0.9998138155547642,
 'CVE': 98.93148406646003,
 'CZK': 22.66673402082031,
 'DJF': 177.6871232609223,
 'DKK': 6.7019919609793215,
 'DOP': 53.19152272164218,
 'DZD': 119.34274409965586,
 'EEK': 14.613691,
 'EGP': 16.07720511706949,
 'ERN': 14.997271221405457,
 'ETB': 32.05851809108992,
 'EUR': 0.896793,
 'FJD': 2.154799735097424,
 'FKP': 0.8127286543881591,
 'GBP': 0.7626229850216301,
 'GEL': 2.8595045055978114,
 'GGP': 0.762586991724273,
 'GHS': 5.703969811782015,
 'GIP': 0.8127286543881591,
 'GMD': 51.210112698066084,
 'GNF': 9433.243543723322,
 'GTQ': 7.710213210909085,
 'GYD': 208.95315892738998,
 'HKD': 7.771802741761024,
 'HNL': 24.620955107496126,
 'HRK': 6.68117883678086,
 'HTG': 98.04386235858559,
 'HUF': 297.2256269064031,
 'IDR': 13915.408684891247,
 'ILS': 3.4695738990144807,
 'IMP': 0.762586991724273,
 'INR': 71.88510961840922,
 'IQD': 1190.2783474179728,
 'ISK': 123.13685356393987,
 'JEP': 0.762586991724273,
 'JMD': 132.27975698054533,
 'JOD': 0.7088539978349114,
 'JPY': 108.35084200194508,
 'KES': 101.28374902975649,
 'KGS': 69.49875700288455,
 'KHR': 4077.2406348518684,
 'KMF': 440.2681126611057,
 'KRW': 1167.012298001102,
 'KWD': 0.3031535470143615,
 'KYD': 0.8333158206642467,
 'KZT': 380.8060776287306,
 'LAK': 8884.345707992981,
 'LBP': 1512.7184319103224,
 'LKR': 181.27287352567373,
 'LRD': 188.5898719606923,
 'LSL': 14.227141634257086,
 'LTL': 2.9521902457411953,
 'LVL': 0.6047773788909242,
 'LYD': 1.4006241770034489,
 'MAD': 9.570721748653536,
 'MDL': 17.097149183986613,
 'MGA': 3707.3215278611083,
 'MKD': 54.98853008451903,
 'MMK': 1463.9827814201503,
 'MNT': 2741.898744038786,
 'MOP': 8.006308072385652,
 'MRO': 356.9333661839532,
 'MTL': 0.683738,
 'MUR': 36.44685189944629,
 'MVR': 15.446876496309033,
 'MWK': 739.8616816114351,
 'MXN': 18.90841889094288,
 'MYR': 4.103215902760414,
 'MZN': 61.69348549364735,
 'NAD': 14.227617545632597,
 'NGN': 362.4319442436125,
 'NIO': 33.73598571455113,
 'NOK': 8.859525187048483,
 'NPR': 114.72077679831429,
 'NZD': 1.5084740932872966,
 'OMR': 0.38495031489252424,
 'PAB': 1.0000417731047018,
 'PEN': 3.325883656884341,
 'PGK': 3.4099649993311183,
 'PHP': 50.88555513688803,
 'PKR': 154.92174760906138,
 'PLN': 3.808140851375767,
 'PYG': 6505.13701813283,
 'QAR': 3.6402771108131886,
 'RON': 4.284632119592828,
 'RSD': 105.3753470959787,
 'RUB': 62.08953974077505,
 'RWF': 934.82591754374,
 'SAR': 3.750763536128672,
 'SBD': 8.30235594261282,
 'SCR': 13.697872194344384,
 'SEK': 9.462162964374256,
 'SGD': 1.3504585188079823,
 'SHP': 1.3206490698972126,
 'SLL': 9773.180235012376,
 'SOS': 579.8925099292278,
 'SRD': 7.456669425608679,
 'SSP': 130.26,
 'STD': 21556.775716275326,
 'SVC': 8.74951667273683,
 'SZL': 14.227462574491389,
 'THB': 30.299379676291412,
 'TJS': 9.697530134507478,
 'TMT': 3.509346492597193,
 'TND': 2.7815120292878404,
 'TOP': 2.2887717869403343,
 'TRY': 5.975652219324139,
 'TTD': 6.7616218567528374,
 'TWD': 30.053397482877582,
 'TZS': 2299.8870140725835,
 'UAH': 23.72886023261564,
 'UGX': 3709.780666922433,
 'UYU': 37.29498596067013,
 'UZS': 9547.5430959611,
 'VEF': 9.985637483411407,
 'VES': 33474.855,
 'VND': 23175.780226685834,
 'VUV': 115.64850703721713,
 'WST': 2.6218657584752543,
 'XAF': 0.0017046745166453216,
 'XAG': 18.213020233016607,
 'XAU': 1570.1510504181074,
 'XCD': 0.3700898111473702,
 'XDR': 1.3833222030509622,
 'XOF': 0.0017047355316867445,
 'XPD': 2047.921359819783,
 'XPF': 0.009334457793393898,
 'XPT': 961.9917076314803,
 'XRH': 0.0001777027137821067,
 'YER': 250.30342971649765,
 'ZAR': 14.326733088424522,
 'ZMK': 8999.527430954533,
 'ZMW': 14.159300267616462,
 'ZWL': 321.9400496084483}

In [32]:
df1 = pd.Series(metalsApiRates).to_frame("Rates")

In [33]:
df1

           Rates
AED     3.672219
AFN    77.235443
ALL   109.199045
AMD   478.728412
ANG     1.684950
..           ...
YER   250.303430
ZAR    14.326733
ZMK  8999.527431
ZMW    14.159300
ZWL   321.940050

[169 rows x 1 columns]

In [34]:
df = pd.DataFrame(metalsApiRes)

In [35]:
df

     success   timestamp        date base        rates       unit
AED     True  1578410520  2020-01-07  USD     3.672219  per ounce
AFN     True  1578410520  2020-01-07  USD    77.235443  per ounce
ALL     True  1578410520  2020-01-07  USD   109.199045  per ounce
AMD     True  1578410520  2020-01-07  USD   478.728412  per ounce
ANG     True  1578410520  2020-01-07  USD     1.684950  per ounce
..       ...         ...         ...  ...          ...        ...
YER     True  1578410520  2020-01-07  USD   250.303430  per ounce
ZAR     True  1578410520  2020-01-07  USD    14.326733  per ounce
ZMK     True  1578410520  2020-01-07  USD  8999.527431  per ounce
ZMW     True  1578410520  2020-01-07  USD    14.159300  per ounce
ZWL     True  1578410520  2020-01-07  USD   321.940050  per ounce

[169 rows x 6 columns]

In [36]:
def convertTime(t):
    return time.strftime('%d/%m/%Y %H:%M:%S', time.gmtime(t))

In [37]:
print(convertTime(1578292380))

06/01/2020 06:33:00

In [38]:
df["timestamp"].map(convertTime)

AED    07/01/2020 15:22:00
AFN    07/01/2020 15:22:00
ALL    07/01/2020 15:22:00
AMD    07/01/2020 15:22:00
ANG    07/01/2020 15:22:00
              ...
YER    07/01/2020 15:22:00
ZAR    07/01/2020 15:22:00
ZMK    07/01/2020 15:22:00
ZMW    07/01/2020 15:22:00
ZWL    07/01/2020 15:22:00
Name: timestamp, Length: 169, dtype: object

In [39]:
df["timestamp"] = df["timestamp"].map(convertTime)

In [40]:
df

     success            timestamp        date base        rates       unit
AED     True  07/01/2020 15:22:00  2020-01-07  USD     3.672219  per ounce
AFN     True  07/01/2020 15:22:00  2020-01-07  USD    77.235443  per ounce
ALL     True  07/01/2020 15:22:00  2020-01-07  USD   109.199045  per ounce
AMD     True  07/01/2020 15:22:00  2020-01-07  USD   478.728412  per ounce
ANG     True  07/01/2020 15:22:00  2020-01-07  USD     1.684950  per ounce
..       ...                  ...         ...  ...          ...        ...
YER     True  07/01/2020 15:22:00  2020-01-07  USD   250.303430  per ounce
ZAR     True  07/01/2020 15:22:00  2020-01-07  USD    14.326733  per ounce
ZMK     True  07/01/2020 15:22:00  2020-01-07  USD  8999.527431  per ounce
ZMW     True  07/01/2020 15:22:00  2020-01-07  USD    14.159300  per ounce
ZWL     True  07/01/2020 15:22:00  2020-01-07  USD   321.940050  per ounce

[169 rows x 6 columns]

In [41]:
df.reset_index()

,index,success,timestamp,date,base,rates,unit
0,AED,True,07/01/2020 15:22:00,2020-01-07,USD,3.672219,per ounce
1,AFN,True,07/01/2020 15:22:00,2020-01-07,USD,77.235443,per ounce
2,ALL,True,07/01/2020 15:22:00,2020-01-07,USD,109.199045,per ounce
3,AMD,True,07/01/2020 15:22:00,2020-01-07,USD,478.728412,per ounce
4,ANG,True,07/01/2020 15:22:00,2020-01-07,USD,1.684950,per ounce
...,...,...,...,...,...,...,...
164,YER,True,07/01/2020 15:22:00,2020-01-07,USD,250.303430,per ounce
165,ZAR,True,07/01/2020 15:22:00,2020-01-07,USD,14.326733,per ounce
166,ZMK,True,07/01/2020 15:22:00,2020-01-07,USD,8999.527431,per ounce
167,ZMW,True,07/01/2020 15:22:00,2020-01-07,USD,14.159300,per ounce
168,ZWL,True,07/01/2020 15:22:00,2020-01-07,USD,321.940050,per ounce

In [42]:
df

     success            timestamp        date base        rates       unit
AED     True  07/01/2020 15:22:00  2020-01-07  USD     3.672219  per ounce
AFN     True  07/01/2020 15:22:00  2020-01-07  USD    77.235443  per ounce
ALL     True  07/01/2020 15:22:00  2020-01-07  USD   109.199045  per ounce
AMD     True  07/01/2020 15:22:00  2020-01-07  USD   478.728412  per ounce
ANG     True  07/01/2020 15:22:00  2020-01-07  USD     1.684950  per ounce
..       ...                  ...         ...  ...          ...        ...
YER     True  07/01/2020 15:22:00  2020-01-07  USD   250.303430  per ounce
ZAR     True  07/01/2020 15:22:00  2020-01-07  USD    14.326733  per ounce
ZMK     True  07/01/2020 15:22:00  2020-01-07  USD  8999.527431  per ounce
ZMW     True  07/01/2020 15:22:00  2020-01-07  USD    14.159300  per ounce
ZWL     True  07/01/2020 15:22:00  2020-01-07  USD   321.940050  per ounce

[169 rows x 6 columns]

In [43]:
df = df.reset_index()

In [44]:
df

,index,success,timestamp,date,base,rates,unit
0,AED,True,07/01/2020 15:22:00,2020-01-07,USD,3.672219,per ounce
1,AFN,True,07/01/2020 15:22:00,2020-01-07,USD,77.235443,per ounce
2,ALL,True,07/01/2020 15:22:00,2020-01-07,USD,109.199045,per ounce
3,AMD,True,07/01/2020 15:22:00,2020-01-07,USD,478.728412,per ounce
4,ANG,True,07/01/2020 15:22:00,2020-01-07,USD,1.684950,per ounce
...,...,...,...,...,...,...,...
164,YER,True,07/01/2020 15:22:00,2020-01-07,USD,250.303430,per ounce
165,ZAR,True,07/01/2020 15:22:00,2020-01-07,USD,14.326733,per ounce
166,ZMK,True,07/01/2020 15:22:00,2020-01-07,USD,8999.527431,per ounce
167,ZMW,True,07/01/2020 15:22:00,2020-01-07,USD,14.159300,per ounce
168,ZWL,True,07/01/2020 15:22:00,2020-01-07,USD,321.940050,per ounce

In [45]:
df = df.rename(columns={'index':'currency'})

In [46]:
df

,currency,success,timestamp,date,base,rates,unit
0,AED,True,07/01/2020 15:22:00,2020-01-07,USD,3.672219,per ounce
1,AFN,True,07/01/2020 15:22:00,2020-01-07,USD,77.235443,per ounce
2,ALL,True,07/01/2020 15:22:00,2020-01-07,USD,109.199045,per ounce
3,AMD,True,07/01/2020 15:22:00,2020-01-07,USD,478.728412,per ounce
4,ANG,True,07/01/2020 15:22:00,2020-01-07,USD,1.684950,per ounce
...,...,...,...,...,...,...,...
164,YER,True,07/01/2020 15:22:00,2020-01-07,USD,250.303430,per ounce
165,ZAR,True,07/01/2020 15:22:00,2020-01-07,USD,14.326733,per ounce
166,ZMK,True,07/01/2020 15:22:00,2020-01-07,USD,8999.527431,per ounce
167,ZMW,True,07/01/2020 15:22:00,2020-01-07,USD,14.159300,per ounce
168,ZWL,True,07/01/2020 15:22:00,2020-01-07,USD,321.940050,per ounce

In [47]:
df[df["currency"] == "XAU"]

,currency,success,timestamp,date,base,rates,unit
156,XAU,True,07/01/2020 15:22:00,2020-01-07,USD,1570.15105,per ounce

In [48]:
dc = pd.read_csv("XAUUSD_Ticks_30.12.2019-30.12.2019.csv")

In [49]:
dc

,Local time,Ask,Bid,AskVolume,BidVolume
0,30.12.2019 07:00:00.172 GMT+0800,1512.082,1511.458,220.0,220.0
1,30.12.2019 07:00:00.273 GMT+0800,1511.902,1511.398,370.0,300.0
2,30.12.2019 07:00:00.388 GMT+0800,1511.902,1511.388,370.0,300.0
3,30.12.2019 07:00:00.510 GMT+0800,1511.902,1511.378,370.0,300.0
4,30.12.2019 07:00:00.575 GMT+0800,1511.902,1511.288,370.0,300.0
...,...,...,...,...,...
83293,30.12.2019 23:59:58.292 GMT+0800,1514.052,1513.788,370.0,300.0
83294,30.12.2019 23:59:58.443 GMT+0800,1514.052,1513.785,370.0,370.0
83295,30.12.2019 23:59:59.176 GMT+0800,1514.052,1513.765,370.0,450.0
83296,30.12.2019 23:59:59.601 GMT+0800,1513.992,1513.765,300.0,450.0
83297,30.12.2019 23:59:59.752 GMT+0800,1514.052,1513.765,370.0,450.0

In [50]:
df

,currency,success,timestamp,date,base,rates,unit
0,AED,True,07/01/2020 15:22:00,2020-01-07,USD,3.672219,per ounce
1,AFN,True,07/01/2020 15:22:00,2020-01-07,USD,77.235443,per ounce
2,ALL,True,07/01/2020 15:22:00,2020-01-07,USD,109.199045,per ounce
3,AMD,True,07/01/2020 15:22:00,2020-01-07,USD,478.728412,per ounce
4,ANG,True,07/01/2020 15:22:00,2020-01-07,USD,1.684950,per ounce
...,...,...,...,...,...,...,...
164,YER,True,07/01/2020 15:22:00,2020-01-07,USD,250.303430,per ounce
165,ZAR,True,07/01/2020 15:22:00,2020-01-07,USD,14.326733,per ounce
166,ZMK,True,07/01/2020 15:22:00,2020-01-07,USD,8999.527431,per ounce
167,ZMW,True,07/01/2020 15:22:00,2020-01-07,USD,14.159300,per ounce
168,ZWL,True,07/01/2020 15:22:00,2020-01-07,USD,321.940050,per ounce

In [51]:
MetalsApiGoldPrice = df[df["currency"] == "XAU"]

In [52]:
MetalsApiGoldPrice

,currency,success,timestamp,date,base,rates,unit
156,XAU,True,07/01/2020 15:22:00,2020-01-07,USD,1570.15105,per ounce

In [29]:
#DCurl stores DukasCopy URL
DCurl = "https://www.dukascopy.com/swiss/english/marketwatch/daily-hl-interbank/"
browser = webdriver.Chrome()

browser.get(DCurl)

# Putting to sleep to ensure webpage is fully rendered
time.sleep(5)

DChtml = browser.page_source
soup = BeautifulSoup(DChtml, "lxml")

# Stores the iframe section where the table is
iframe = soup.find_all("iframe")[1]

# Just for testing/visual purposes
print(iframe)
    
# Trying to open the URL but it doesn't work - Access to the Page Denied
response = urllib.request.urlopen(iframe.attrs['src'])
iframe_soup = BeautifulSoup(response)

<iframe border="0" frameborder="0" height="600" marginheight="0" marginwidth="0" scrolling="no" src="https://freeserv.dukascopy.com/2.0/?path=daily_highs_lows/index&amp;showHeader=true&amp;tableBorderColor=%23D92626&amp;timezone=utc&amp;availableInstruments=l%3A&amp;width=100%25&amp;height=600&amp;adv=popup" width="100%"></iframe>

HTTPError: HTTP Error 403: Forbidden